
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 48
#define YY_END_OF_BUFFER 49
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[239] =
    {   0,
        0,    0,   49,   47,   46,   46,   47,   47,   47,   47,
       39,   38,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,    0,
       44,    0,    0,    0,   42,    1,    2,   43,   39,    0,
        0,   39,   39,    0,   39,   38,   38,   38,   38,   45,
       45,    0,    0,   45,   45,   45,   45,   45,   45,   10,
       45,   45,   45,   45,   45,   45,   18,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   44,
        0,    0,    0,    0,   40,    0,    0,    0,   42,    2,
        0,   43,    0,   41,   39,   39,   39,   39,   37,   38,

       38,   38,   38,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   16,   45,   45,   20,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,    0,    0,    0,    0,    0,   42,
        0,   43,   41,   39,   37,   37,   37,   38,    3,   45,
        5,    6,   45,   45,   45,   45,   12,   13,   45,   45,
       17,   45,   21,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   34,   45,   45,    0,    0,
        0,    0,   37,   37,   37,   37,    4,    7,   45,   45,
       45,   45,   15,   45,   45,   45,   45,   25,   45,   45,

       45,   45,   45,   45,   32,   45,   45,   36,   37,   45,
       45,   11,   14,   19,   45,   45,   24,   26,   27,   28,
       29,   30,   45,   45,   45,   45,    9,   45,   45,   31,
       45,   45,    8,   22,   23,   33,   35,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    5,    1,
        1,    6,    7,    1,    7,    8,    9,   10,   11,   11,
       11,   11,   11,   11,   11,   12,   13,    1,    1,    1,
        1,    1,   14,    1,   15,   15,   15,   15,   16,   17,
       18,   18,   18,   18,   18,   19,   18,   18,   18,   18,
       18,   18,   18,   18,   20,   18,   18,   21,   18,   18,
        1,   22,    1,    1,   18,    1,   23,   24,   25,   26,

       27,   28,   29,   30,   31,   18,   32,   33,   34,   35,
       36,   37,   18,   38,   39,   40,   41,   42,   43,   44,
       45,   46,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[47] =
    {   0,
        1,    1,    2,    3,    4,    1,    1,    1,    1,    5,
        5,    6,    6,    3,    6,    6,    6,    7,    7,    7,
        7,    3,    5,    5,    6,    6,    6,    5,    7,    7,
        7,    7,    7,    7,    8,    7,    7,    8,    7,    8,
        7,    8,    7,    8,    7,    7
    } ;

static yyconst flex_int16_t yy_base[249] =
    {   0,
        0,    0,  209, 1070, 1070, 1070,   43,  186,   38,   46,
       58,   95,   46,   71,   51,   83,  127,   74,   90,   94,
       37,  118,  119,  129,  137,  139,  181,  128,  151,   50,
      186,  122,  107,  134,  218, 1070,    0,  242,   65,  268,
      184,  151,  128,    0,  179,    0,  181,  188,  182,    0,
      196,   76,  176,  220,  241,  260,  262,  270,  274,  271,
      285,  286,  290,  295,  305,  306,  309,  314,  325,  328,
      326,  336,  340,  350,  354,  179,  362,  364,  373,  403,
      175,  131,  214,    0, 1070,  252,    0,  401, 1070,    0,
      408, 1070,   77,  435,  162, 1070,  157,  139,  369,  224,

     1070,  112,   86,  394,  402,  404,  403,  419,  420,  437,
      439,  442,  447,  456,  457,  458,  459,  461,  473,  475,
      477,  478,  492,  497,  508,  506,  511,  520,  528,  531,
      539,  542,  543,  551,  572,  591,  575,  615,  228,  634,
      276,  658, 1070, 1070,  333,  214,  396, 1070,  569,  625,
      599,  629,  643,  651,  662,  666,  665,  670,  674,  684,
      685,  693,  695,  696,  704,  707,  716,  721,  724,  732,
      736,  744,  747,  752,  735,  755,  756,  767,   96,    0,
      244,    0,  262, 1070,   97,   20,  770,  772,  775,  784,
      786,  789,  798,  800,  803,  814,  812,  823,  826,  835,

      843,  834,  831,  853,  852,  855,  863,  872, 1070,  873,
      875,  874,  877,  889,  893,  901,  898,  909,  910,  912,
      913,  921,  924,  932,  933,  944,  942,  947,  952,  961,
      963,  971,  972,  973,  981,  982,  983, 1070, 1019, 1027,
     1031, 1037, 1043, 1051, 1055, 1057, 1061, 1063
    } ;

static yyconst flex_int16_t yy_def[249] =
    {   0,
      238,    1,  238,  238,  238,  238,  239,  240,  238,  238,
      238,  238,  241,  241,  241,  241,  241,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,  239,
      238,  242,  240,  243,  238,  238,  244,  238,   11,  238,
      238,  238,  238,  245,  238,   12,  238,  238,  238,  246,
       17,  239,  240,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,  246,   17,   17,   17,  238,
      238,  238,  239,  247,  238,  240,  248,  238,  238,  244,
      238,  238,  238,  238,  238,  238,  238,  238,  245,  238,

      238,  238,  238,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,  239,  239,  240,  240,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,  239,  136,
      240,  138,  238,  238,  238,  238,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,

       17,   17,   17,   17,   17,   17,   17,   17,  238,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    0,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238
    } ;

static yyconst flex_int16_t yy_nxt[1117] =
    {   0,
        4,    5,    6,    7,    8,    4,    4,    9,   10,   11,
       12,   12,   12,    4,   13,   13,   13,   13,   14,   14,
       13,    4,   15,   16,   17,   18,   19,   20,   21,   13,
       22,   13,   23,   13,   13,   13,   13,   24,   25,   26,
       27,   28,   29,   13,   13,   13,   31,   35,   35,   35,
       35,   36,  209,   31,   37,   50,   50,   50,   50,   51,
       50,   50,   50,   50,   32,   38,   51,   39,   39,   40,
       40,   32,   66,   41,   52,   53,   42,   43,   44,   31,
       50,   50,   50,   50,   41,  238,   94,   94,   94,   94,
       45,   54,   50,   50,   50,   50,   51,   32,   43,   31,

       59,   44,   38,   51,   46,   46,   46,   46,  238,   60,
       41,   85,   51,   47,   48,  209,   51,   32,  148,   51,
       55,   41,   61,   51,   62,   51,   64,   49,   34,   65,
      148,   83,   83,   63,   52,   48,   50,   50,   50,   50,
       51,   51,   81,   86,   86,   67,   97,   51,   51,   56,
       51,   51,   68,   51,   69,   70,   57,   51,   51,   51,
       98,   51,   58,   78,   51,   84,   71,   72,   51,   95,
       96,  144,   51,   51,   51,  144,   73,   87,   52,   74,
       79,   96,   52,   75,   52,   53,   51,   80,   80,   52,
       93,   96,   76,   94,   94,   94,   94,   34,   96,  100,

      101,  101,   96,   51,   81,   81,  102,   34,  238,  238,
       51,   95,  238,  238,  100,   77,   51,   31,   51,   96,
      103,  101,  101,  135,  135,   51,   82,   35,   35,   35,
       35,   51,  185,   88,   89,   32,   89,  140,  140,  140,
      140,  238,   51,  101,   88,   89,  186,  238,   85,   51,
       89,   35,   35,   35,   35,   51,   85,   91,   92,  104,
       92,  137,  137,   51,  101,   34,  238,  105,   91,   92,
       51,  238,  238,   34,   92,   38,   51,   40,   40,   40,
       40,  184,   51,   41,  107,  142,  142,  142,  142,   51,
      238,   51,   51,   51,   41,   51,   51,   51,  106,   51,

       51,  109,  184,   51,  108,   51,   51,   51,   51,   51,
      238,  110,   51,  238,   51,   51,  238,   51,  238,   51,
       51,   51,  238,  111,   51,   51,  112,   51,   51,  113,
      114,   51,  238,  238,   51,   51,   51,  238,   51,  238,
       51,   51,  115,   51,   51,  116,  117,   51,   51,   51,
       51,  183,  184,  118,   51,   51,  120,   51,   51,  119,
       51,  123,  126,   51,  124,   51,  121,  122,  238,   51,
      238,   51,   51,  184,  238,   51,   51,  127,  238,   51,
      128,  125,  238,   51,   51,   51,   51,  145,  146,   51,
      129,   51,  130,   51,  132,   51,  133,   51,  238,   51,

      131,  147,   51,  134,   80,   80,   52,  139,   51,  146,
      140,  140,  140,  140,  141,  184,   51,  142,  142,  142,
      142,   81,   81,   51,  150,   51,   51,  238,  183,  149,
      151,   51,   51,   51,  238,  238,  184,   51,   51,   51,
      152,   51,  155,   82,   94,   94,   94,   94,   51,   51,
      238,  143,  238,  143,   51,   51,  238,  153,  154,   51,
      156,   51,  143,  238,   51,  157,   51,  143,   51,   51,
      238,   51,   51,  159,   51,  158,   51,   51,  160,   51,
       51,   51,   51,   51,  238,   51,   51,   51,   51,  162,
       51,   51,   51,  161,   51,   51,   51,   51,  238,   51,

       51,  163,   51,  238,   51,  164,   51,   51,   51,  238,
       51,  238,   51,   51,   51,  238,  165,  238,  166,   51,
      238,   51,  238,  238,  238,  238,   51,   51,   51,  167,
       51,  168,   51,   51,  169,   51,  238,   51,  238,  238,
       51,   51,   51,   51,  238,  170,   51,  238,  238,   51,
       51,  171,  238,   51,  173,   51,  238,   51,  238,  172,
       51,   51,  238,   51,   51,  177,  174,  176,   51,  175,
      238,   51,   51,   51,   51,   31,  238,   51,   51,   85,
       51,  179,  179,  178,  181,  181,   51,  238,  238,  238,
      238,   51,  238,   32,   31,  238,   34,  238,   51,  238,

      180,  180,  180,  180,   51,  180,  180,  180,  238,  238,
      238,  238,   32,  180,  180,  180,  180,  180,  180,   85,
      238,   51,  238,  238,  182,  182,  182,  182,   51,  182,
      182,  182,  238,  238,   51,  238,   34,  182,  182,  182,
      182,  182,  182,  140,  140,  140,  140,   51,  238,  238,
       89,   51,   89,  238,   51,  238,  187,  238,   51,  238,
       51,   89,  238,  238,   51,   51,   89,  142,  142,  142,
      142,  238,   51,   51,   92,  238,   92,  238,   51,  238,
       51,  189,  188,  238,   51,   92,   51,   51,   51,  238,
       92,   51,   51,  238,   51,   51,   51,   51,  191,   51,

       51,   51,  190,   51,  238,   51,   51,   51,  238,   51,
      238,  192,  238,   51,   51,   51,  238,   51,   51,   51,
       51,  238,   51,  193,   51,   51,   51,  194,   51,   51,
       51,   51,  238,   51,  195,  238,   51,  238,   51,   51,
      238,  196,   51,   51,  197,   51,   51,  199,  238,  238,
       51,   51,  238,   51,   51,  198,   51,   51,   51,  200,
      202,   51,  201,  206,   51,   51,   51,   51,  203,   51,
       51,   51,  204,   51,   51,  238,   51,   51,   51,   51,
      238,   51,   51,  238,   51,   51,  205,   51,  238,   51,
       51,   51,   51,  208,   51,  207,   51,   51,  238,   51,

      238,   51,   51,  238,   51,   51,   51,   51,   51,  210,
       51,   51,  212,   51,  238,   51,  211,  238,   51,   51,
       51,   51,   51,  213,   51,   51,  214,   51,  238,   51,
      238,  238,   51,   51,   51,   51,   51,  238,   51,  238,
      238,   51,  215,   51,  216,   51,  217,   51,   51,   51,
      238,  218,   51,   51,  238,   51,   51,   51,   51,  238,
      222,   51,  219,   51,   51,   51,   51,  220,  238,   51,
       51,  238,   51,  221,   51,   51,  238,   51,   51,  223,
      238,   51,   51,  238,   51,   51,  238,   51,   51,  224,
       51,  238,   51,  225,   51,   51,   51,   51,   51,   51,

      238,   51,   51,   51,   51,  238,   51,   51,   51,   51,
       51,   51,   51,  226,  227,   51,  238,  238,   51,  228,
       51,  238,   51,   51,   51,  229,  238,   51,   51,  238,
       51,   51,   51,   51,   51,   51,   51,  238,   51,   51,
      238,   51,   51,   51,   51,   51,   51,   51,   51,  238,
       51,  230,  238,   51,   51,   51,   51,  238,  231,   51,
      238,   51,   51,  238,   51,  232,   51,   51,   51,   51,
      233,   51,  238,   51,   51,  238,   51,   51,  238,   51,
      238,   51,   51,   51,  234,   51,  238,   51,  236,  238,
       51,  235,   51,   51,   51,   51,   51,  237,   51,  238,

       51,   51,   51,   51,   51,   51,   51,   51,   51,  238,
       51,   51,   51,  238,  238,  238,   51,   51,   51,   30,
      238,   30,   30,   30,   30,   30,   30,   33,  238,   33,
      238,   33,   33,   33,   33,   51,   51,   51,   51,   30,
       30,   30,  238,  238,   30,   33,   33,   33,  238,  238,
       33,   90,  238,   90,   90,   90,   90,   90,   90,   99,
       99,   50,   50,   50,   50,  136,  136,  138,  138,    3,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,

      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238
    } ;

static yyconst flex_int16_t yy_chk[1117] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    7,    9,    9,    9,
        9,   10,  186,   30,   10,   13,   13,   13,   13,   21,
       15,   15,   15,   15,    7,   11,   21,   11,   11,   11,
       11,   30,   21,   11,   14,   14,   11,   11,   11,   52,
       14,   14,   14,   14,   11,   39,   93,   93,   93,   93,
       11,   15,   16,   16,   16,   16,   18,   52,   11,  179,

       18,   11,   12,   18,   12,   12,   12,   12,   39,   18,
       12,   33,   19,   12,   12,  185,   20,  179,  103,   19,
       16,   12,   19,   20,   19,   19,   20,   12,   33,   20,
      102,   32,   32,   19,   82,   12,   17,   17,   17,   17,
       22,   23,   82,   34,   34,   22,   43,   22,   23,   17,
       28,   24,   22,   22,   23,   24,   17,   28,   24,   25,
       43,   26,   17,   28,   24,   32,   25,   25,   26,   42,
       42,   98,   25,   29,   26,   97,   25,   34,   81,   25,
       29,   95,   76,   26,   27,   27,   29,   31,   31,   31,
       41,   42,   27,   41,   41,   41,   41,   53,   45,   47,

       47,   49,   95,   27,   31,   31,   48,    8,    3,    0,
       27,   45,    0,    0,   49,   27,   27,   83,   51,   45,
       48,   47,   49,   83,   83,   51,   31,   35,   35,   35,
       35,   51,  146,   35,   35,   83,   35,  139,  139,  139,
      139,    0,   54,  100,   35,   35,  146,    0,  181,   54,
       35,   38,   38,   38,   38,   54,   86,   38,   38,   54,
       38,   86,   86,   55,  100,  181,    0,   55,   38,   38,
       55,    0,    0,   86,   38,   40,   55,   40,   40,   40,
       40,  183,   56,   40,   57,  141,  141,  141,  141,   56,
        0,   57,   58,   60,   40,   56,   59,   57,   56,   58,

       60,   59,  183,   59,   58,   58,   60,   61,   62,   59,
        0,   60,   63,    0,   61,   62,    0,   64,    0,   63,
       61,   62,    0,   61,   64,   63,   62,   65,   66,   63,
       64,   67,    0,    0,   65,   66,   68,    0,   67,    0,
       65,   66,   65,   68,   67,   66,   68,   69,   71,   68,
       70,  145,  145,   68,   69,   71,   70,   70,   72,   69,
       69,   71,   73,   70,   72,   72,   70,   70,    0,   73,
        0,   72,   74,  145,    0,   73,   75,   73,    0,   74,
       74,   72,    0,   75,   77,   74,   78,   99,   99,   75,
       75,   77,   77,   78,   78,   79,   78,   77,    0,   78,

       77,   99,   79,   79,   80,   80,   80,   88,   79,   99,
       88,   88,   88,   88,   91,  147,  104,   91,   91,   91,
       91,   80,   80,  104,  105,  107,  106,    0,  147,  104,
      106,  105,  107,  106,    0,    0,  147,  105,  107,  106,
      107,  108,  109,   80,   94,   94,   94,   94,  108,  109,
        0,   94,    0,   94,  108,  109,    0,  108,  108,  110,
      110,  111,   94,    0,  112,  111,  110,   94,  111,  113,
        0,  112,  110,  113,  111,  112,  113,  112,  114,  115,
      116,  117,  113,  118,    0,  114,  115,  116,  117,  117,
      118,  114,  115,  116,  117,  119,  118,  120,    0,  121,

      122,  119,  119,    0,  120,  120,  121,  122,  119,    0,
      120,    0,  121,  122,  123,    0,  121,    0,  122,  124,
        0,  123,    0,    0,    0,    0,  124,  123,  126,  123,
      125,  124,  124,  127,  125,  126,    0,  125,    0,    0,
      127,  126,  128,  125,    0,  126,  127,    0,    0,  128,
      129,  127,    0,  130,  129,  128,    0,  129,    0,  128,
      130,  131,    0,  129,  132,  133,  130,  132,  131,  131,
        0,  132,  133,  134,  131,  135,    0,  132,  133,  137,
      134,  135,  135,  134,  137,  137,  134,    0,    0,    0,
        0,  149,    0,  135,  136,    0,  137,    0,  149,    0,

      136,  136,  136,  136,  149,  136,  136,  136,    0,    0,
        0,    0,  136,  136,  136,  136,  136,  136,  136,  138,
        0,  151,    0,    0,  138,  138,  138,  138,  151,  138,
      138,  138,    0,    0,  151,    0,  138,  138,  138,  138,
      138,  138,  138,  140,  140,  140,  140,  150,    0,    0,
      140,  152,  140,    0,  150,    0,  150,    0,  152,    0,
      150,  140,    0,    0,  152,  153,  140,  142,  142,  142,
      142,    0,  153,  154,  142,    0,  142,    0,  153,    0,
      154,  154,  153,    0,  155,  142,  154,  157,  156,    0,
      142,  155,  158,    0,  157,  156,  159,  155,  156,  158,

      157,  156,  155,  159,    0,  158,  160,  161,    0,  159,
        0,  159,    0,  160,  161,  162,    0,  163,  164,  160,
      161,    0,  162,  160,  163,  164,  165,  162,  162,  166,
      163,  164,    0,  165,  164,    0,  166,    0,  167,  165,
        0,  165,  166,  168,  166,  167,  169,  168,    0,    0,
      168,  167,    0,  169,  170,  167,  168,  175,  171,  169,
      171,  170,  170,  175,  175,  171,  172,  170,  172,  173,
      175,  171,  173,  172,  174,    0,  173,  176,  177,  172,
        0,  174,  173,    0,  176,  177,  174,  174,    0,  178,
      176,  177,  187,  178,  188,  177,  178,  189,    0,  187,

        0,  188,  178,    0,  189,  187,  190,  188,  191,  189,
      189,  192,  191,  190,    0,  191,  190,    0,  192,  190,
      193,  191,  194,  192,  192,  195,  194,  193,    0,  194,
        0,    0,  195,  193,  197,  194,  196,    0,  195,    0,
        0,  197,  195,  196,  196,  198,  197,  197,  199,  196,
        0,  199,  198,  203,    0,  199,  202,  200,  198,    0,
      203,  199,  200,  202,  200,  201,  203,  201,    0,  202,
      200,    0,  201,  202,  205,  204,    0,  206,  201,  204,
        0,  205,  204,    0,  206,  207,    0,  205,  204,  206,
      206,    0,  207,  207,  208,  210,  212,  211,  207,  213,

        0,  208,  210,  212,  211,    0,  213,  208,  210,  212,
      211,  214,  213,  210,  211,  215,    0,    0,  214,  215,
      217,    0,  215,  216,  214,  216,    0,  217,  215,    0,
      216,  218,  219,  217,  220,  221,  216,    0,  218,  219,
        0,  220,  221,  222,  218,  219,  223,  220,  221,    0,
      222,  223,    0,  223,  224,  225,  222,    0,  224,  223,
        0,  224,  225,    0,  227,  225,  226,  224,  225,  228,
      226,  227,    0,  226,  229,    0,  228,  227,    0,  226,
        0,  229,  228,  230,  228,  231,    0,  229,  231,    0,
      230,  229,  231,  232,  233,  234,  230,  232,  231,    0,

      232,  233,  234,  235,  236,  237,  232,  233,  234,    0,
      235,  236,  237,    0,    0,    0,  235,  236,  237,  239,
        0,  239,  239,  239,  239,  239,  239,  240,    0,  240,
        0,  240,  240,  240,  240,  241,  241,  241,  241,  242,
      242,  242,    0,    0,  242,  243,  243,  243,    0,    0,
      243,  244,    0,  244,  244,  244,  244,  244,  244,  245,
      245,  246,  246,  246,  246,  247,  247,  248,  248,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,

      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 19 "lex.l"
#include <stdio.h>
#include<string.h>
void do_nothing();
void copy_file();
void print_struct();
#line 784 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 29 "lex.l"

#line 968 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 239 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1070 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 30 "lex.l"
{ /* comment(); */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 31 "lex.l"
{ /* do nothing */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 34 "lex.l"
{ ; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 35 "lex.l"
{ ; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 36 "lex.l"
{ ; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 37 "lex.l"
{ ; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 38 "lex.l"
{ ; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 39 "lex.l"
{ ; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 40 "lex.l"
{ ; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 41 "lex.l"
{ ; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 42 "lex.l"
{ ; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 43 "lex.l"
{ ; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 44 "lex.l"
{ ; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 45 "lex.l"
{ ; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 46 "lex.l"
{ ; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 47 "lex.l"
{ ; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 48 "lex.l"
{ ; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 49 "lex.l"
{ ; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 50 "lex.l"
{ ; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 51 "lex.l"
{ ; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 52 "lex.l"
{ ; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 53 "lex.l"
{ ; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 54 "lex.l"
{ ; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 55 "lex.l"
{ ; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 56 "lex.l"
{ ; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 57 "lex.l"
{ ; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 58 "lex.l"
{ ; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 59 "lex.l"
{ ; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 60 "lex.l"
{ ; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 61 "lex.l"
{ ; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 62 "lex.l"
{ ; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 63 "lex.l"
{ ; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 64 "lex.l"
{ ; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 65 "lex.l"
{ ; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 66 "lex.l"
{ ; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 67 "lex.l"
{ ; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 69 "lex.l"
{ print_struct(yytext);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 70 "lex.l"
{  print_struct(yytext);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 71 "lex.l"
{ print_struct(yytext);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 72 "lex.l"
{  print_struct(yytext);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 74 "lex.l"
{print_struct(yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 75 "lex.l"
{ 	print_struct(yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 76 "lex.l"
{ 	print_struct(yytext);}
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 78 "lex.l"
{ 	print_struct(yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 80 "lex.l"
{ printf("%s\n",yytext); print_struct(yytext);}
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 83 "lex.l"
{ /* whitespace */ }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 84 "lex.l"
{ /* ignore rest */}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 86 "lex.l"
ECHO;
	YY_BREAK
#line 1293 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 239 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 239 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 238);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 86 "lex.l"



void copy_file(){
   FILE *fp1, *fp2;
   char ch;
   fp1 = fopen("outfinal.txt", "r");
   fp2 = fopen("out.txt", "w");

   while (1)
   {
      ch = fgetc(fp1);
 
      if (ch == EOF)
         break;
      else
         putc(ch, fp2);
   }

   fclose(fp1);
   fclose(fp2);

}

void do_nothing()
{
	 return;
}

void print_struct(char lit[])
{
	char p[20];
	int chk=0,count;
	long offset; 
	FILE *fp=fopen("out.txt","a+");
	FILE *ft=fopen("outfinal.txt","w+");
	fseek( fp,0, SEEK_SET );

while(fscanf(fp, "%s %d", p, &count) == 2)
{
	if(strcmp(p,lit)==0)
	{
	 fprintf(ft,"%s %d\n",p,++count);
	 chk=1;
	}

	if(chk==1)
	{
		chk=-1;
	}
	else
		fprintf(ft,"%s %d\n",p,count);
}

if(chk!=-1)
{
	 fprintf(ft,"%s %d\n",lit,1);
}

fclose(ft);
fclose(fp);
copy_file();}

int main(int argc,char* argv[]) 
{
  yyin=fopen(argv[1],"r");
  yylex(); 
  return 1;
}


